# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(376, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.textSayi1 = QtWidgets.QLineEdit(self.centralwidget)
        self.textSayi1.setGeometry(QtCore.QRect(70, 20, 113, 20))
        self.textSayi1.setObjectName("textSayi1")
        self.textSayi2 = QtWidgets.QLineEdit(self.centralwidget)
        self.textSayi2.setGeometry(QtCore.QRect(70, 60, 113, 20))
        self.textSayi2.setObjectName("textSayi2")
        self.buttonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAdd.setGeometry(QtCore.QRect(70, 90, 75, 23))
        self.buttonAdd.setObjectName("buttonAdd")
        self.buttonSub = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSub.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.buttonSub.setObjectName("buttonSub")
        self.buttonDiv = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDiv.setGeometry(QtCore.QRect(160, 120, 75, 23))
        self.buttonDiv.setObjectName("buttonDiv")
        self.buttonMul = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMul.setGeometry(QtCore.QRect(70, 120, 75, 23))
        self.buttonMul.setObjectName("buttonMul")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 47, 13))
        self.label_3.setObjectName("label_3")
        self.textSonuc = QtWidgets.QLineEdit(self.centralwidget)
        self.textSonuc.setEnabled(True)
        self.textSonuc.setGeometry(QtCore.QRect(110, 160, 113, 20))
        self.textSonuc.setObjectName("textSonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 376, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sayı 1: "))
        self.label_2.setText(_translate("MainWindow", "Sayı 2: "))
        self.buttonAdd.setText(_translate("MainWindow", "Toplama"))
        self.buttonSub.setText(_translate("MainWindow", "Çıkarma"))
        self.buttonDiv.setText(_translate("MainWindow", "Bölme"))
        self.buttonMul.setText(_translate("MainWindow", "Çarpma"))
        self.label_3.setText(_translate("MainWindow", "Sonuç:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
