# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnKayit = QtWidgets.QPushButton(self.centralwidget)
        self.btnKayit.setGeometry(QtCore.QRect(20, 280, 129, 23))
        self.btnKayit.setObjectName("btnKayit")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(10, 310, 151, 121))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 261, 261))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(30, 30, 131, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSinema = QtWidgets.QCheckBox(self.widget)
        self.cbSinema.setObjectName("cbSinema")
        self.verticalLayout.addWidget(self.cbSinema)
        self.cbSpor = QtWidgets.QCheckBox(self.widget)
        self.cbSpor.setObjectName("cbSpor")
        self.verticalLayout.addWidget(self.cbSpor)
        self.cbGezi = QtWidgets.QCheckBox(self.widget)
        self.cbGezi.setObjectName("cbGezi")
        self.verticalLayout.addWidget(self.cbGezi)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 10, 261, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 131, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbAudi = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbAudi.setObjectName("cbAudi")
        self.verticalLayout_2.addWidget(self.cbAudi)
        self.cbBMW = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbBMW.setObjectName("cbBMW")
        self.verticalLayout_2.addWidget(self.cbBMW)
        self.cbHyundai = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbHyundai.setObjectName("cbHyundai")
        self.verticalLayout_2.addWidget(self.cbHyundai)
        self.lblResult_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblResult_2.setGeometry(QtCore.QRect(290, 310, 151, 121))
        self.lblResult_2.setText("")
        self.lblResult_2.setObjectName("lblResult_2")
        self.btnKayit_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnKayit_2.setGeometry(QtCore.QRect(290, 280, 129, 23))
        self.btnKayit_2.setObjectName("btnKayit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnKayit.setText(_translate("MainWindow", "Kayıt Et"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema.setText(_translate("MainWindow", "Sinema"))
        self.cbSpor.setText(_translate("MainWindow", "Spor"))
        self.cbGezi.setText(_translate("MainWindow", "Gezi"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbAudi.setText(_translate("MainWindow", "Audi"))
        self.cbBMW.setText(_translate("MainWindow", "BWM"))
        self.cbHyundai.setText(_translate("MainWindow", "Hyundai"))
        self.btnKayit_2.setText(_translate("MainWindow", "Kayıt Et"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
