# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'income.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 71, 21))
        self.label.setObjectName("label")
        self.totalIncome = QtWidgets.QLineEdit(self.centralwidget)
        self.totalIncome.setGeometry(QtCore.QRect(40, 60, 113, 20))
        self.totalIncome.setObjectName("totalIncome")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 70, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 100, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 130, 71, 16))
        self.label_5.setObjectName("label_5")
        self.totalTaxes = QtWidgets.QLineEdit(self.centralwidget)
        self.totalTaxes.setGeometry(QtCore.QRect(360, 70, 113, 20))
        self.totalTaxes.setObjectName("totalTaxes")
        self.totalBank = QtWidgets.QLineEdit(self.centralwidget)
        self.totalBank.setGeometry(QtCore.QRect(360, 100, 113, 20))
        self.totalBank.setObjectName("totalBank")
        self.totalFee = QtWidgets.QLineEdit(self.centralwidget)
        self.totalFee.setGeometry(QtCore.QRect(360, 130, 113, 20))
        self.totalFee.setObjectName("totalFee")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 240, 47, 13))
        self.label_6.setObjectName("label_6")
        self.netIncome = QtWidgets.QLineEdit(self.centralwidget)
        self.netIncome.setGeometry(QtCore.QRect(290, 240, 113, 20))
        self.netIncome.setObjectName("netIncome")
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setGeometry(QtCore.QRect(230, 190, 75, 23))
        self.calcButton.setObjectName("calcButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Toplam Gelir"))
        self.label_2.setText(_translate("MainWindow", "Toplam Gider"))
        self.label_3.setText(_translate("MainWindow", "Faturalar"))
        self.label_4.setText(_translate("MainWindow", "Kredi Ödemesi"))
        self.label_5.setText(_translate("MainWindow", "Aidatlar"))
        self.label_6.setText(_translate("MainWindow", "Net Kalan"))
        self.calcButton.setText(_translate("MainWindow", "Hesapla"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
