# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radiobutton.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(270, 40, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_2.addWidget(self.radioButton_5, 0, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_2.addWidget(self.radioButton_6, 1, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_2.addWidget(self.radioButton_7, 0, 1, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_2.addWidget(self.radioButton_8, 1, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 171, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 3, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 0, 0, 1, 1)
        self.labelUlke = QtWidgets.QLabel(self.centralwidget)
        self.labelUlke.setGeometry(QtCore.QRect(30, 170, 81, 41))
        self.labelUlke.setText("")
        self.labelUlke.setTextFormat(QtCore.Qt.PlainText)
        self.labelUlke.setObjectName("labelUlke")
        self.pbUlke = QtWidgets.QPushButton(self.centralwidget)
        self.pbUlke.setGeometry(QtCore.QRect(50, 260, 75, 23))
        self.pbUlke.setObjectName("pbUlke")
        self.pbEgitim = QtWidgets.QPushButton(self.centralwidget)
        self.pbEgitim.setGeometry(QtCore.QRect(250, 260, 75, 23))
        self.pbEgitim.setObjectName("pbEgitim")
        self.labelEgitim = QtWidgets.QLabel(self.centralwidget)
        self.labelEgitim.setGeometry(QtCore.QRect(270, 160, 101, 51))
        self.labelEgitim.setText("")
        self.labelEgitim.setTextFormat(QtCore.Qt.PlainText)
        self.labelEgitim.setObjectName("labelEgitim")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_5.setText(_translate("MainWindow", "İlkokul"))
        self.radioButton_6.setText(_translate("MainWindow", "Lise"))
        self.radioButton_7.setText(_translate("MainWindow", "Üniversite"))
        self.radioButton_8.setText(_translate("MainWindow", "Yüksek Lisans"))
        self.radioButton.setText(_translate("MainWindow", "Türkiye"))
        self.radioButton_2.setText(_translate("MainWindow", "Almanya"))
        self.radioButton_3.setText(_translate("MainWindow", "Yunanistan"))
        self.radioButton_4.setText(_translate("MainWindow", "Azerbaycan"))
        self.pbUlke.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.pbEgitim.setText(_translate("MainWindow", "Eğitim Seçimi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
